### ISSUE TITLE
Big refactoring needed here.

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spikewidgets#13]
I think we would need a refactoring here with basically 4 submoules:
  * one with all matplotlib function to simplify the plotting
  * one with all jupyter widget stuff (lazy dep on jupyter)
  * one with QT5 stuff to make a GUI
  * one with common tools share by all (probe display, waveform average, ...)

For the Qt5 submodule I propose to depend on pyqtgraphn and also on  [ephyviewer](https://github.com/NeuralEnsemble/ephyviewer) it is a module that plotting (using pyqtgraph) all ephy stuff (signals, spike, trigegrs, video, ...)
I spend lot of times make ephyviewer fast. It do not ncecessary load everything in memero but have a on demand load.
 Internally ephyviewer must DataSource class to mapped the underlying dataset making possible to deal with several data model. For instance it can be used  with numpy, neo object, or directly with ephy files. making source for SpikeExtractor and RecordingExtractor should be easy.

@colehurwitz31 : could you have a look in ephyviewer example and tell what you think ?

**Comment by colehurwitz31** [comment]
Sure, I will take a look! I like the refactoring idea.
