### ISSUE TITLE
Make a BasePlotWidget

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spikewidgets#20]
We must have a BasePlotWidget that define the API.

This BaseWidget should handle the backend:
  * matplotlib
  * or Jeremy JS framework

In case of matplotlib, we must have a clear scenario of who handle the figure.
Sometimes we have:
  * plt.gca()
  * fig, ax = plt.subplots()

We must offer the ability to the user to provide a fig and in that case the plot would be done on it.
And if None then a fig is created.

The base widget also would impose some mandatory attr and methods.

With this we could start generic unitest taht would be applied to all widget.

**Comment by alejoe91** [comment]
I'm making a PR with ax arg for all widgets, but this is a better idea.

I think we could pass either the figure or the axis, so one could make a nice summary plot.

In case the axis is passed, we can create subplots with gridspace. We can improve my PR
