### ISSUE TITLE
Switch unitest to pytest style.

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spikewidgets#38]
The actual (one file) is in unittest.TestCase style.

i propose to switch to pytest style meaning only a list of function that starts with test_

This is more convinient to work only on one stuff is it OK ?

**Comment by alejoe91** [comment]
the way it's done now the rec and sort objects are only simulated once, so it's more efficient.

**Comment by samuelgarcia** [comment]
There is setup also in pytest.
