### ISSUE TITLE
This module should not depend on a sorter module.

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spikewidgets#5]
I am exploring this place.
My feeling is that this module should not depend on a sorter module
So ml_ms4alg should be removed from setup.py.

**Comment by alejoe91** [comment]
Hi @samuelgarcia! Definitely it should be removed, thanks for spotting it.
Note that spikewidgets is in heavy development and we will go through a round of cleaning soon.

**Comment by magland** [comment]
Thanks @samuelgarcia , making that change now...

**Comment by samuelgarcia** [comment]
@magland where did you make the change ?

**Comment by magland** [comment]
In the master branch. no longer depends on ml_ms4alg.

**Comment by samuelgarcia** [comment]
Oups.
I did not see the commit.
I am sorry.
Do you work directly on the main repo ?

**Comment by magland** [comment]
yeah, i just pushed the change directly to master.
