### ISSUE TITLE
Empty raster plots

### ISSUE THREAD

**Issue by wuffi** [SpikeInterface/spikewidgets#69]
There could be a problem with the `plot_rasters()` method (I'm working with the development version of *spikewidgets* from GitHub both on *Linux* (Ubuntu 18.04) and Windows 10:
The plots generated with it have the right number of units and time range, but the plot is empty for my dataset:
![Figure 2020-10-28 120559](https://user-images.githubusercontent.com/2758427/97429220-67b83600-1917-11eb-92af-8db9ba44ac9a.png)
Other plots like the autocorrelograms or the inter-spike intervals are good (i.e. containing data points for all units).
![Figure 2020-10-28 121132](https://user-images.githubusercontent.com/2758427/97429222-67b83600-1917-11eb-84a1-9db1b93d278e.png)
![Figure 2020-10-28 120539](https://user-images.githubusercontent.com/2758427/97429218-671f9f80-1917-11eb-826f-d5ebd23fc91a.png)
I will try to see what's going wrong.

**Comment by alejoe91** [comment]
Hi @wuffi 

This is strange! What dataset are you using? Can you provide some minimal code to reproduce the issue? I'll check if it's the same on my side as well

**Comment by wuffi** [comment]
The problem could be due to the positional argument `shank_id=None` in `get_unit_spike_train()` function in line 293 of `neuroscopeextractors.py` (in *spikeextractors*):
> `def get_unit_spike_train(self, unit_id, shank_id=None, start_frame=None, end_frame=None):`
>  `...`

Depending on whether the argument `shank_id` is given or not, the other arguments get shifted.  
Changing the line to
> `def get_unit_spike_train(self, unit_id, start_frame=None, end_frame=None):`
>  `...`

solves the problem, but could potentially interfere with other functionality.
For generating the raster plot, it might be easiest to omit information about the shanks/tetrodes like the function for plotting the ISI seems to do and just plot the spikes of all cells in one graph.
![Figure 2020-10-28 155842](https://user-images.githubusercontent.com/2758427/97454060-a27d9680-1936-11eb-852e-964147f0f344.png)

The example for my data (recording with four tetrodes) would look like this:
```
import spikeextractors as se
import spikewidgets as sw

sorting = se.NeuroscopeMultiSortingExtractor('neuroscope_recording')
sw.plot_isi_distribution(sorting)  # this works
sw.plot_rasters(sorting)  # this doesn't
```
I haven't figured quite out where the information about the shanks (tetrodes) comes from - it is presumably extracted from *Neuroscopes* xml parameter file.

**Comment by alejoe91** [comment]
Thanks for catching it! The shank_id arg should be last. I'll make a PR to fix it.

If there are multiple shanks, the res and club files have an appended I'd, e.mg .res.0.clu.0
