### ISSUE TITLE
plot_unit_waveforms returns empty graph

### ISSUE THREAD

**Issue by hamdanspam** [SpikeInterface/spikewidgets#75]
I am using Colab to access my large dataset from the cloud. Other plotting functions work without a hitch, but for `plot_unit_waveforms`, I get an empty graph. I am using Recording and Sorting objects that I extracted with `KiloSortRecordingExtractor` and `KiloSortSortingExtractor`, respectively. When I try to plot waveforms with unit ids in my `good_units` list like so,
```
sw.plot_unit_waveforms(
    KS_recording, KS_sort,
    channel_ids=KS_sort.get_units_property(
        unit_ids=good_units[0:2],
        property_name='ch'
    ),
    unit_ids=good_units[0:2],
    max_channels=2,
    channel_locs=False,
    plot_templates=True,
    radius=None,
    show_all_channels=False,
    max_spikes_per_unit=50
)
```

I get this error: 

> /usr/local/lib/python3.6/dist-packages/MEAutility/plotting.py:605: RuntimeWarning: divide by zero encountered in true_divide
>   signals_norm = signals / vscale * mea_pitch[1]
> /usr/local/lib/python3.6/dist-packages/MEAutility/plotting.py:605: RuntimeWarning: invalid value encountered in true_divide
>   signals_norm = signals / vscale * mea_pitch[1]
> /usr/local/lib/python3.6/dist-packages/MEAutility/plotting.py:605: RuntimeWarning: invalid value encountered in true_divide
>   signals_norm = signals / vscale * mea_pitch[1]
> /usr/local/lib/python3.6/dist-packages/MEAutility/plotting.py:605: RuntimeWarning: divide by zero encountered in true_divide
>   signals_norm = signals / vscale * mea_pitch[1]
> /usr/local/lib/python3.6/dist-packages/MEAutility/plotting.py:605: RuntimeWarning: invalid value encountered in true_divide
>   signals_norm = signals / vscale * mea_pitch[1]
> /usr/local/lib/python3.6/dist-packages/MEAutility/plotting.py:605: RuntimeWarning: invalid value encountered in true_divide
>   signals_norm = signals / vscale * mea_pitch[1]

And an empty graph with titles:
![image](https://user-images.githubusercontent.com/15875720/104035261-c7885400-5186-11eb-8e09-99b7d4a4fa0c.png)

I am not sure how to make this reproducible given the massive size of the dataset, but I can share the link to Colab if that would help.

**Comment by alejoe91** [comment]
Hi, does the `ch` property only have one channel? What is the geometry of the probe? Can you try with a higher number of `max_channels`?

Cheers
Alessio

**Comment by hamdanspam** [comment]
Hi Alessio,

Thanks for your response. Yes, the `ch` property only has one property, it's the best channel from the cluster_info.tsv from sorting with phy. 

When I try with `max_channels` as10, 50, or 100, I get the same result.

Cheers,
Dan

**Comment by alejoe91** [comment]
Ok I see. Try to leave `channel_ids=None` then. `channel_ids` allows you to manually select which channels you want to use, and it should be a list of channels.

**Comment by hamdanspam** [comment]
Hi Alessio,

I get the same result. There seems to be some kind of divide by zero issue. Do you know what could be causing that?

Many thanks,
Dan

**Comment by alejoe91** [comment]
Mmm yeah I think that the cause is that vscale 0. Vscale is computed from the waveforms to space the different waveform plots. Is it possible that one waveform is all zeros? If you could give me access to the data I can take a look in the next days.

Cheers
Alessio

**Comment by hamdanspam** [comment]
Hi Alessio,

That would be great, but this data is not necessarily mine to share. I will check with my collaborators and check back here with a reproducible example if possible in the days to come. In the meantime, would you be willing to give me a sense of where to look on my own?

Many thanks,
Dan

**Comment by hamdanspam** [comment]
Hi Alessio,

Sorry for the delay. I've got the data serialized and a notebook that reproduces everything, but I'm not sure how to share it. I'm not sure how this usually works- can I share a Google Drive link privately? 

Best,
Dan

**Comment by hamdanspam** [comment]
@alejoe91 figured out that the issue came from the fact that my recording was shortened but the spike sorting applied to the whole recording, leading to some zeroed values. This will be checked against in the future.
