### ISSUE TITLE
Problem with activity map widget

### ISSUE THREAD

**Issue by abhijithkrishnan93** [SpikeInterface/spikewidgets#77]
Hi, 

I am having a little trouble with the plot_activity_map() widget. As I understand u dont have to do a full sorting for this, but the recording extractor object is necessary. But after I use the MCSRaw recording extractor to load the data.

recording=se.MCSRawRecordingExtractor(filename='Data0585.raw')

sw.plot_activity_map(recording,channel_ids=[2,5,7,9],trange=[0,100])

 I get an error :

assert 'location' in self._recording.get_shared_channel_property_names(), "Activity map requires 'location'" \
    104                                                                                   "property"
    105 

AssertionError: Activity map requires 'location' property

eventhough recording has the get_shared_channel_property_names() attribute. 

Am I doing something wrong?

**Comment by alejoe91** [comment]
Hi!

The activity map widget requires channel locations, as the error is suggesting.

When you run `get_shared_channel_property_names()`, do you get `location` in the list? It seems that you don't have the location of the channels as a property. You can load it either manually, or using a prb file, or using [probeinterface](https://probeinterface.readthedocs.io/en/main/)

**Comment by abhijithkrishnan93** [comment]
No I am only getting the group as the property. I did load a prb file, like how it is mentioned in the tutorials, but got the same error. I will try using probeinterface

Thanks !

**Comment by alejoe91** [comment]
Note that prb files can also only contain group info, without location. You can specify the location with the `geometry` entry in the prb file

**Comment by abhijithkrishnan93** [comment]
I load the probe file with
recording_prb = recording.load_probe_file('mea_recent.prb')

The prb file has the location in the geometry entry

**Comment by alejoe91** [comment]
Ok, then you need to pass the `recording_prb`, as probe loading is not in place

**Comment by abhijithkrishnan93** [comment]
Yes my mistake. Sorry. Thanks for responding. I was passing the wrong object.

**Comment by alejoe91** [comment]
No worries!

**Comment by abhijithkrishnan93** [comment]
Again I ran into a problem. This maybe a matplotlib issue, but I am not able to plot the activity map in a for loop:

for i in range(0,10):
        
    activity_map=sw.plot_activity_map(recording_cmr,channel_ids=None,trange=[i,i+1],activity='rate',colorbar=True,background=True)
        
    plt.savefig('./activity_map_585/foo_%d.png' %i )

This gives the same figure saved 10 times. Insted of at different time points.

**Comment by alejoe91** [comment]
Yes, that is because the spike rate is saved the first time it's computed. You can force recomputation with the `recompute_info=True`. Not sure this will work directly in spikweidgets. If it doesn't, I'll show you how to do it using a combination of spiketoolkit and spikweidgets

**Comment by abhijithkrishnan93** [comment]
It looks like it is working. But looks to be pretty slow. Is there a better way of doing this?

**Comment by alejoe91** [comment]
Well it takes some time for sure because it needs to detect spikes on all channels first and then render them. Unfortunately there's no better way

**Comment by abhijithkrishnan93** [comment]
Thank you. Again for your help
